before_install:
  - "gem update --system"
  - "gem install bundler"
script:
  - "travis_retry bundle exec rake default --trace"
  - "bundle exec rubocop -D"
language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6  
env:
  global:
  - TRAVISCI=1
  matrix:
    - NEO4J_GEM_VERSION="~> 9.0"
    - NEO4J_GEM_VERSION="~> 8.0"
